In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

path_str = r"/home/admin123/Documents/SAP/Div_academy/data/world_population.csv"
csv_path = Path(path_str)
df = pd.read_csv(csv_path)
df2 = df.set_index('CCA3')
df2.head(3)

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
CCA3,,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56

In [3]:
df_pop = df2.loc['AFG':'AZE',['Country','2022 Population']]
df_area = df2.iloc[10:20,[1,-4]]
df_area

         Country  Area (km²)
CCA3
ABW        Aruba       180.0
AUS    Australia   7692024.0
AUT      Austria     83871.0
AZE   Azerbaijan     86600.0
BHS      Bahamas     13943.0
BHR      Bahrain       765.0
BGD   Bangladesh    147570.0
BRB     Barbados       430.0
BLR      Belarus    207600.0
BEL      Belgium     30528.0

In [4]:
adamlar = ['shahriyar','nijat','murad','esger','aynur']
yemekler = ['dolma','katlet','ash','lule','bughlama']
rengler = ['cyan','qara','yashil','sari','goy']

s_yemek = pd.Series(yemekler,index=adamlar)
s_reng = pd.Series(rengler,index=adamlar)
s_yemek

shahriyar       dolma
nijat          katlet
murad             ash
esger            lule
aynur        bughlama
dtype: object

In [5]:
pd.concat([s_yemek,s_reng],
          ignore_index=True,
          axis = 'columns')

                  0       1
shahriyar     dolma    cyan
nijat        katlet    qara
murad           ash  yashil
esger          lule    sari
aynur      bughlama     goy

In [6]:
pd.concat([df_pop,df_area],
          axis='columns',
          keys=['pop','area'])

                      pop                        area
                  Country 2022 Population     Country Area (km²)
CCA3
AFG           Afghanistan      41128771.0         NaN        NaN
ALB               Albania       2842321.0         NaN        NaN
DZA               Algeria      44903225.0         NaN        NaN
ASM        American Samoa         44273.0         NaN        NaN
AND               Andorra         79824.0         NaN        NaN
AGO                Angola      35588987.0         NaN        NaN
AIA              Anguilla         15857.0         NaN        NaN
ATG   Antigua and Barbuda         93763.0         NaN        NaN
ARG             Argentina      45510318.0         NaN        NaN
ARM               Armenia       2780469.0         NaN        NaN
ABW                 Aruba        106445.0       Aruba      180.0
AUS             Australia      26177413.0   Australia  7692024.0
AUT               Austria       8939617.0     Austria    83871.0
AZE            Azerbaijan      10358074.0  Azerbaijan    86600.0
BHS                   NaN             NaN     Bahamas    13943.0
BHR                   NaN             NaN     Bahrain      765.0
BGD                   NaN             NaN  Bangladesh   147570.0
BRB                   NaN             NaN    Barbados      430.0
BLR                   NaN             NaN     Belarus   207600.0
BEL                   NaN             NaN     Belgium    30528.0

In [7]:
yemekler = ['dolma', 'katlet', 'ash', 'lule', 'xengel']
adamlar_y = ['shahriyar', 'nijat', 'murad', 'asgar', 'isa']

rengler = ['cyan', 'qara', 'yashil', 'sari']
adamlar_r = ['shahriyar', 'nijat', 'murad', 'aynur']

s_yemek = pd.Series(yemekler, index=adamlar_y, name='yemek')
s_reng = pd.Series(rengler, index=adamlar_r, name='reng')

s_yemek

shahriyar     dolma
nijat        katlet
murad           ash
asgar          lule
isa          xengel
Name: yemek, dtype: object

In [8]:
s_reng

shahriyar      cyan
nijat          qara
murad        yashil
aynur          sari
Name: reng, dtype: object

In [9]:
pd.merge(s_yemek,s_reng,how='inner',left_index=True,right_index =True)

            yemek    reng
shahriyar   dolma    cyan
nijat      katlet    qara
murad         ash  yashil

In [10]:
df_area

         Country  Area (km²)
CCA3
ABW        Aruba       180.0
AUS    Australia   7692024.0
AUT      Austria     83871.0
AZE   Azerbaijan     86600.0
BHS      Bahamas     13943.0
BHR      Bahrain       765.0
BGD   Bangladesh    147570.0
BRB     Barbados       430.0
BLR      Belarus    207600.0
BEL      Belgium     30528.0

In [11]:
df_pop

                  Country  2022 Population
CCA3
AFG           Afghanistan       41128771.0
ALB               Albania        2842321.0
DZA               Algeria       44903225.0
ASM        American Samoa          44273.0
AND               Andorra          79824.0
AGO                Angola       35588987.0
AIA              Anguilla          15857.0
ATG   Antigua and Barbuda          93763.0
ARG             Argentina       45510318.0
ARM               Armenia        2780469.0
ABW                 Aruba         106445.0
AUS             Australia       26177413.0
AUT               Austria        8939617.0
AZE            Azerbaijan       10358074.0

In [12]:
pd.merge(df_pop,
         df_area,
         how='inner',
         left_index=True,
         right_index=True,
         suffixes=['_pop','_area'])

pd.merge(df_pop,
         df_area.drop('Country',axis='columns'),
         how='inner',
         left_index=True,
         right_index=True,
         suffixes=['_pop','_area'])

         Country  2022 Population  Area (km²)
CCA3
ABW        Aruba         106445.0       180.0
AUS    Australia       26177413.0   7692024.0
AUT      Austria        8939617.0     83871.0
AZE   Azerbaijan       10358074.0     86600.0

In [13]:
pd.merge(
    df_pop,
    df_area,
    how='left',
    on='Country'

)

                Country  2022 Population  Area (km²)
0           Afghanistan       41128771.0         NaN
1               Albania        2842321.0         NaN
2               Algeria       44903225.0         NaN
3        American Samoa          44273.0         NaN
4               Andorra          79824.0         NaN
5                Angola       35588987.0         NaN
6              Anguilla          15857.0         NaN
7   Antigua and Barbuda          93763.0         NaN
8             Argentina       45510318.0         NaN
9               Armenia        2780469.0         NaN
10                Aruba         106445.0       180.0
11            Australia       26177413.0   7692024.0
12              Austria        8939617.0     83871.0
13           Azerbaijan       10358074.0     86600.0

In [14]:
rng = np.random.RandomState(0)
data2 = rng.randint(0,10,6)
data1 = np.arange(6)

df = pd.DataFrame({'s' : ['A','B','C']*2,
              'data1': data1,
              'data2': data2})
df

   s  data1  data2
0  A      0      5
1  B      1      0
2  C      2      3
3  A      3      3
4  B      4      7
5  C      5      9

In [15]:
df.groupby('s').mean()

   data1  data2
s
A    1.5    4.0
B    2.5    3.5
C    3.5    6.0

In [16]:
df2.groupby('Continent')['2022 Population'].sum()

Continent
Africa           1.425529e+09
Asia             4.720042e+09
Europe           7.377132e+08
North America    6.002961e+08
Oceania          4.502050e+07
South America    4.368166e+08
Name: 2022 Population, dtype: float64

In [17]:
for g_name,d in df2.groupby('Continent'):
    print(g_name, d.shape, d['2022 Population'].mean())

Africa (57, 16) 25455879.67857143
Asia (50, 16) 96327387.30612245
Europe (50, 16) 15055371.81632653
North America (40, 16) 15007403.4
Oceania (23, 16) 2046386.3181818181
South America (14, 16) 31201186.285714287

In [18]:
df2.describe()

,Rank,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
count,234.000000,2.300000e+02,2.330000e+02,2.300000e+02,2.270000e+02,2.270000e+02,2.290000e+02,2.290000e+02,2.300000e+02,2.320000e+02,230.000000,232.000000,234.000000
mean,117.500000,3.463225e+07,3.360071e+07,3.206600e+07,3.027016e+07,2.684050e+07,1.933046e+07,1.628288e+07,1.586650e+07,5.816637e+05,456.811652,1.009553,0.427051
std,67.694165,1.378892e+08,1.358732e+08,1.315071e+08,1.260742e+08,1.133525e+08,8.130962e+07,6.934547e+07,6.835586e+07,1.769133e+06,2083.740364,0.013390,1.714977
min,1.000000,5.100000e+02,5.200000e+02,5.640000e+02,5.960000e+02,6.510000e+02,7.000000e+02,7.330000e+02,7.520000e+02,1.000000e+00,0.026100,0.912000,0.000000
25%,59.250000,4.197385e+05,4.064710e+05,3.942950e+05,3.827265e+05,3.294700e+05,2.619280e+05,2.237520e+05,1.458805e+05,2.567250e+03,36.598125,1.001925,0.010000
50%,117.500000,5.762857e+06,5.456681e+06,5.244415e+06,4.889741e+06,4.491202e+06,3.785847e+06,3.135123e+06,2.511718e+06,7.714100e+04,95.346750,1.007900,0.070000
75%,175.750000,2.265372e+07,2.152263e+07,1.973085e+07,1.682585e+07,1.562547e+07,1.188276e+07,9.817257e+06,8.817329e+06,4.146432e+05,236.884000,1.016650,0.280000
max,234.000000,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,9.823725e+08,8.225344e+08,1.709824e+07,23172.266700,1.069100,17.880000

In [19]:
df2.groupby('Continent').agg({
    '2022 Population': 'mean'
})

               2022 Population
Continent
Africa            2.545588e+07
Asia              9.632739e+07
Europe            1.505537e+07
North America     1.500740e+07
Oceania           2.046386e+06
South America     3.120119e+07

In [20]:
csv_path = Path('/home/admin123/Documents/SAP/Div_academy/data/1.04. Real-life example.csv')
df = pd.read_csv(csv_path)

df_yeni = df.copy()
df_yeni.set_index('Brand', inplace=True)

yeni_cols = [
['General', 'General', 'General', 'General', 'Main', 'Main', 'Main', 'Main'],
['Price', 'Body', 'Mileage', 'EngineV', 'Engine Type', 'Registration', 'Year', 'Model']
]

df_yeni.columns = yeni_cols
df_yeni.head(3)

               General                               Main                     \
                 Price   Body Mileage EngineV Engine Type Registration  Year
Brand
BMW             4200.0  sedan     277     2.0      Petrol          yes  1991
Mercedes-Benz   7900.0    van     427     2.9      Diesel          yes  1999
Mercedes-Benz  13300.0  sedan     358     5.0         Gas          yes  2003


                      Model
Brand
BMW                     320
Mercedes-Benz  Sprinter 212
Mercedes-Benz         S 500

In [21]:
df_yeni[df_yeni.loc[:,('General','Body')] != 'sedan']

                General                                   Main               \
                  Price       Body Mileage EngineV Engine Type Registration
Brand
Mercedes-Benz    7900.0        van     427     2.9      Diesel          yes
Audi            23000.0  crossover     240     4.2      Petrol          yes
Toyota          18300.0  crossover     120     2.0      Petrol          yes
Mercedes-Benz  199999.0  crossover       0     5.5      Petrol          yes
Audi            14200.0      vagon     200     2.7      Diesel          yes
...                 ...        ...     ...     ...         ...          ...
Renault          7000.0        van     210     1.5      Diesel          yes
BMW             12090.0      hatch     145     1.6      Petrol          yes
Renault          2100.0      vagon     237     1.9      Diesel           no
Volkswagen      11500.0        van     163     2.5      Diesel          yes
Volkswagen      13500.0        van     124     2.0      Diesel          yes


               Year              Model
Brand
Mercedes-Benz  1999       Sprinter 212
Audi           2007                 Q7
Toyota         2011              Rav 4
Mercedes-Benz  2016             GLS 63
Audi           2006                 A6
...             ...                ...
Renault        2005             Kangoo
BMW            2010                116
Renault        2001             Laguna
Volkswagen     2008   T5 (Transporter)
Volkswagen     2013  T5 (Transporter)

[2696 rows x 8 columns]

In [22]:
df.groupby(['Brand', "Body"])['Price'].sum()

Brand          Body
Audi           crossover    2856303.25
               hatch         367214.00
               other         990265.00
               sedan        2961797.75
               vagon         993838.00
               van             3000.00
BMW            crossover    7342248.00
               hatch         226112.00
               other        1400452.00
               sedan        6161624.25
               vagon         608035.00
Mercedes-Benz  crossover    9490101.00
               hatch         336956.00
               other        4434401.00
               sedan        8378068.00
               vagon         238490.00
               van          3200041.00
Mitsubishi     crossover    2165697.85
               hatch          90435.25
               other         306371.20
               sedan         980414.00
               vagon          61600.00
               van            43997.00
Renault        crossover     263093.41
               hatch         302317.15
               other         293935.00
               sedan         415068.28
               vagon         905217.28
               van          1484386.80
Toyota         crossover    7202984.94
               hatch         586874.39
               other         885008.00
               sedan        2787515.63
               vagon         181775.25
               van           171050.00
Volkswagen     crossover    2514893.55
               hatch         904019.78
               other        1082566.00
               sedan        3302031.23
               vagon         900857.14
               van          3213375.58
Name: Price, dtype: float64

In [23]:
df.head()

,Brand,Price,Body,Mileage,EngineV,Engine Type,Registration,Year,Model
0,BMW,4200.0,sedan,277,2.0,Petrol,yes,1991,320
1,Mercedes-Benz,7900.0,van,427,2.9,Diesel,yes,1999,Sprinter 212
2,Mercedes-Benz,13300.0,sedan,358,5.0,Gas,yes,2003,S 500
3,Audi,23000.0,crossover,240,4.2,Petrol,yes,2007,Q7
4,Toyota,18300.0,crossover,120,2.0,Petrol,yes,2011,Rav 4

In [24]:
mask1 = df['Body'] == 'crossover'
mask2 = df['Body'] == 'hatch'
df.loc[mask1 | mask2, :].groupby(['Brand', "Body"]).agg({
    'Price': 'sum',
    'Mileage' : 'mean',
    # 'Model': 'nunique',
    'Model' : 'unique'

})

                              Price     Mileage  \
Brand         Body
Audi          crossover  2856303.25   98.753247
              hatch       367214.00  123.157895
BMW           crossover  7342248.00  103.125654
              hatch       226112.00  109.750000
Mercedes-Benz crossover  9490101.00   90.148810
              hatch       336956.00  126.391304
Mitsubishi    crossover  2165697.85  121.875912
              hatch        90435.25  204.473684
Renault       crossover   263093.41   72.263158
              hatch       302317.15  124.658537
Toyota        crossover  7202984.94  114.273543
              hatch       586874.39   96.101695
Volkswagen    crossover  2514893.55  109.779070
              hatch       904019.78  153.723214

                                                                     Model
Brand         Body
Audi          crossover                       [Q7, A6 Allroad, Q5, A6, Q3]
              hatch                              [A3, A6, A1, A7, A5, 100]
BMW           crossover                  [X5, X6, X5 M, X6 M, X1, X3, 535]
              hatch      [116, 118, 1 Series, X6, 4 Series Gran Coupe, ...
Mercedes-Benz crossover  [GLS 63, GLS 500, G 55 AMG, ML 350, GLS 350, G...
              hatch      [A 150, A 170, B 200, A 140, A 160, B-Class El...
Mitsubishi    crossover  [Outlander, Pajero Wagon, Outlander XL, Pajero...
              hatch      [Colt, Lancer X Sportback, Galant, Carisma, La...
Renault       crossover  [Koleos, Duster, Kangoo, Scenic, Captur, Sande...
              hatch      [Clio, Kangoo, Megane, Sandero, Laguna, 5, Sce...
Toyota        crossover  [Rav 4, Land Cruiser 100, Land Cruiser Prado, ...
              hatch       [Auris, Prius, Yaris, IQ, Corolla, Aygo, Carina]
Volkswagen    crossover  [Touareg, Tiguan, Golf IV, Amarok, Passat CC, ...
              hatch      [Polo, Golf GTI, Lupo, Golf IV, Golf Plus, Up,...

In [25]:
ds_brand_ave = df.groupby('Brand')['Price'].transform('mean')
df['brand_avg'] = ds_brand_ave

In [26]:
df.groupby('Brand')['Price'].mean()
df2 = df.groupby('Brand', as_index=False).agg({
    'Price' : 'mean'
})
df3 = df.drop('brand_avg', axis='columns')
pd.merge(df3, df2, how='left', on='Brand')

,Brand,Price_x,Body,Mileage,EngineV,Engine Type,Registration,Year,Model,Price_y
0,BMW,4200.0,sedan,277,2.0,Petrol,yes,1991,320,23525.368087
1,Mercedes-Benz,7900.0,van,427,2.9,Diesel,yes,1999,Sprinter 212,30608.048122
2,Mercedes-Benz,13300.0,sedan,358,5.0,Gas,yes,2003,S 500,30608.048122
3,Audi,23000.0,crossover,240,4.2,Petrol,yes,2007,Q7,18489.633484
4,Toyota,18300.0,crossover,120,2.0,Petrol,yes,2011,Rav 4,22591.220287
...,...,...,...,...,...,...,...,...,...,...
4340,Mercedes-Benz,125000.0,sedan,9,3.0,Diesel,yes,2014,S 350,30608.048122
4341,BMW,6500.0,sedan,1,3.5,Petrol,yes,1999,535,23525.368087
4342,BMW,8000.0,sedan,194,2.0,Petrol,yes,1985,520,23525.368087
4343,Toyota,14200.0,sedan,31,NaN,Petrol,yes,2014,Corolla,22591.220287
4344,Volkswagen,13500.0,van,124,2.0,Diesel,yes,2013,T5 (Transporter),13125.267930

In [27]:
df.pivot_table(
    values='Price',
    index= 'Brand',
    columns = 'Body',
    aggfunc='mean'
)

Body,crossover,hatch,other,sedan,vagon,van
Brand,,,,,,
Audi,39127.441781,20400.777778,28293.285714,14171.281100,9375.830189,3000.000000
BMW,41955.702857,20555.636364,23736.474576,16129.906414,14477.023810,NaN
Mercedes-Benz,66831.697183,14650.260870,33092.544776,23080.077135,11924.500000,18823.770588
Mitsubishi,16042.206296,4759.750000,11783.507692,7659.484375,7700.000000,6285.285714
Renault,13847.021579,7373.589024,8645.147059,7156.349655,8381.641481,7573.402041
Toyota,34137.369384,10296.041930,23919.135135,14078.361768,15147.937500,21381.250000
Volkswagen,29586.982941,8218.361636,11640.494624,12413.651241,9583.586596,12359.136846

In [28]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
result = pd.concat([ser1, ser2])
print(result)

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [29]:
df6 = pd.DataFrame({
    'name': ['Peter', 'Paul', 'Mary'],
    'food': ['fish', 'beans', 'bread']},
    columns=['name', 'food'])
df6

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

In [30]:
df7 = pd.DataFrame({
    'name': ['Mary', 'Joseph'],
    'drink': ['wine', 'beer']},
    columns=['name', 'drink'])
df7

     name drink
0    Mary  wine
1  Joseph  beer

In [31]:
import pandas as pd
import numpy as np
df6 = pd.DataFrame({
    'name': ['Peter', 'Paul', 'Mary'],
    'food': ['fish', 'beans', 'bread']},
    columns=['name', 'food'])
df7 = pd.DataFrame({
    'name': ['Mary', 'Joseph'],
    'drink': ['wine', 'beer']},
    columns=['name', 'drink'])
print(pd.merge(df6, df7,how='right')) # inner join by default, equivalent to how = 'inner'

     name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer

In [32]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [1, 2, 3, 4]})
df9 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
'rank': [3, 1, 4, 2]})
pd.merge(df8, df9, on="name", )

   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [33]:
df1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']}, index=[0, 1])
df2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']}, index=[2, 3])
df1

    A   B
0  A0  B0
1  A1  B1

In [34]:
df2

    A   B
2  A2  B2
3  A3  B3

In [35]:
pd.concat([df1,df2])

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [36]:
pd.concat([df1,df2],axis='columns',)

     A    B    A    B
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2  NaN  NaN   A2   B2
3  NaN  NaN   A3   B3

In [37]:
df3 = pd.DataFrame({'A': ['A4', 'A5'], 'B': ['B4', 'B5']}, index=[0, 1])
df3

    A   B
0  A4  B4
1  A5  B5

In [38]:
pd.concat([df1,df3],ignore_index=True)

    A   B
0  A0  B0
1  A1  B1
2  A4  B4
3  A5  B5

In [39]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2'], 'A': ['A0', 'A1', 'A2']})
right = pd.DataFrame({'key': ['K0', 'K1', 'K3'], 'B': ['B0', 'B1', 'B3']})
left

  key   A
0  K0  A0
1  K1  A1
2  K2  A2

In [40]:
right

  key   B
0  K0  B0
1  K1  B1
2  K3  B3

In [65]:
pd.merge(left,right,how='right')

  key    A   B
0  K0   A0  B0
1  K1   A1  B1
2  K3  NaN  B3

In [42]:
pd.merge(left,right,on='key')

  key   A   B
0  K0  A0  B0
1  K1  A1  B1

In [43]:
pd.merge(left,right,how='outer')

  key    A    B
0  K0   A0   B0
1  K1   A1   B1
2  K2   A2  NaN
3  K3  NaN   B3

In [44]:
pd.merge(left,right,how='left')

  key   A    B
0  K0  A0   B0
1  K1  A1   B1
2  K2  A2  NaN

In [45]:
pd.merge(left,right,how='right')

  key    A   B
0  K0   A0  B0
1  K1   A1  B1
2  K3  NaN  B3

In [46]:
df_employees = pd.DataFrame({'emp_id': [1, 2, 3, 4], 'name': ['Alice', 'Bob', 'Charlie', 'David']})
df_salaries = pd.DataFrame({'id': [1, 2, 3, 5], 'salary': [50000, 60000, 70000, 80000]})
df_employees

   emp_id     name
0       1    Alice
1       2      Bob
2       3  Charlie
3       4    David

In [47]:
df_salaries

   id  salary
0   1   50000
1   2   60000
2   3   70000
3   5   80000

In [48]:
pd.merge(df_employees,df_salaries,left_on='emp_id',right_on='id').drop('id',axis='columns')

   emp_id     name  salary
0       1    Alice   50000
1       2      Bob   60000
2       3  Charlie   70000

In [49]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [50]:
planets.groupby('method')['number'].count()

method
Astrometry                         2
Eclipse Timing Variations          9
Imaging                           38
Microlensing                      23
Orbital Brightness Modulation      3
Pulsar Timing                      5
Pulsation Timing Variations        1
Radial Velocity                  553
Transit                          397
Transit Timing Variations          4
Name: number, dtype: int64

In [51]:
planets.groupby('method')['orbital_period'].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [52]:
planets.groupby('method').agg({
    'mass' : 'min',
    'mass' : 'median',
    'mass' : 'max',
})

                                mass
method
Astrometry                       NaN
Eclipse Timing Variations       6.05
Imaging                          NaN
Microlensing                     NaN
Orbital Brightness Modulation    NaN
Pulsar Timing                    NaN
Pulsation Timing Variations      NaN
Radial Velocity                25.00
Transit                         1.47
Transit Timing Variations        NaN

In [53]:
planets2 = planets.dropna(how='any')
planets.groupby('method')['mass'].agg(['min','median','max'])

                                  min  median    max
method
Astrometry                        NaN     NaN    NaN
Eclipse Timing Variations      4.2000   5.125   6.05
Imaging                           NaN     NaN    NaN
Microlensing                      NaN     NaN    NaN
Orbital Brightness Modulation     NaN     NaN    NaN
Pulsar Timing                     NaN     NaN    NaN
Pulsation Timing Variations       NaN     NaN    NaN
Radial Velocity                0.0036   1.260  25.00
Transit                        1.4700   1.470   1.47
Transit Timing Variations         NaN     NaN    NaN

In [54]:
df = pd.DataFrame({
    'Team': ['A', 'A', 'B', 'B', 'C', 'C'],
    'Points': [10, 15, 10, 20, 10, 5],
    'Assists': [5, 7, 5, 10, 5, 2]
})
df

  Team  Points  Assists
0    A      10        5
1    A      15        7
2    B      10        5
3    B      20       10
4    C      10        5
5    C       5        2

In [55]:
df.groupby('Team').agg({
    'Points' : 'sum',
    'Assists' : 'sum'
})
df.rename

<bound method DataFrame.rename of   Team  Points  Assists
0    A      10        5
1    A      15        7
2    B      10        5
3    B      20       10
4    C      10        5
5    C       5        2>

In [56]:
df.groupby('Team').filter(lambda x: x["Points"].mean() > 12)

  Team  Points  Assists
0    A      10        5
1    A      15        7
2    B      10        5
3    B      20       10

In [57]:
def funct(x):
    return x - x.mean()

df['Points_Standardized'] = df.groupby('Team')['Points'].transform(funct)
df

  Team  Points  Assists  Points_Standardized
0    A      10        5                 -2.5
1    A      15        7                  2.5
2    B      10        5                 -5.0
3    B      20       10                  5.0
4    C      10        5                  2.5
5    C       5        2                 -2.5

In [58]:
def ope(x):
    if x['Assists'].sum() > 10:
        return x['Points'] * 2
    else:
        return x['Points']
df.groupby('Team').apply(ope)

/tmp/ipykernel_13964/3679874652.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Team').apply(ope)

Team
A     0    20
      1    30
B     2    20
      3    40
C     4    10
      5     5
Name: Points, dtype: int64

In [59]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [60]:
titanic.pivot_table(values='survived',index='sex',columns='class',aggfunc='mean',margins=True)

/tmp/ipykernel_13964/3546666595.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table(values='survived',index='sex',columns='class',aggfunc='mean',margins=True)

class      First    Second     Third       All
sex
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838

In [61]:
titanic.pivot_table(index=['sex','embarked'],columns='class',aggfunc={
    'survived' : 'sum',
    'fare' : 'mean'
})

/tmp/ipykernel_13964/1372646608.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table(index=['sex','embarked'],columns='class',aggfunc={

                       fare                       survived
class                 First     Second      Third    First Second Third
sex    embarked
female C         115.640309  25.268457  14.694926       42      7    15
       Q          90.000000  12.350000  10.307833        1      2    24
       S          99.026910  21.912687  18.670077       46     61    33
male   C          93.536707  25.421250   9.352237       17      2    10
       Q          90.000000  12.350000  11.924251        0      0     3
       S          52.949947  19.232474  13.307149       28     15    34

In [62]:
titanicseries = pd.Series(titanic['fare'])
titanicseries.cumsum

<bound method Series.cumsum of 0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: fare, Length: 891, dtype: float64>

In [63]:
df

  Team  Points  Assists  Points_Standardized
0    A      10        5                 -2.5
1    A      15        7                  2.5
2    B      10        5                 -5.0
3    B      20       10                  5.0
4    C      10        5                  2.5
5    C       5        2                 -2.5

In [64]:
df['Team'].nlargest


str.find