In [2]:
import numpy as np
import pandas as pd
from pathlib import Path

df = pd.read_csv(Path('/home/admin123/Documents/SAP/Div_academy/data/hotel_bookings.csv'))
df.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [4]:
import pandas as pd

df = pd.read_csv(Path('/home/admin123/Documents/SAP/Div_academy/data/hotel_bookings.csv'))

df = df.replace('', pd.NA)

numeric_cols = ['lead_time', 'arrival_date_year', 'arrival_date_week_number',
                'arrival_date_day_of_month', 'stays_in_weekend_nights',
                'stays_in_week_nights', 'adults', 'children', 'babies',
                'previous_cancellations', 'previous_bookings_not_canceled',
                'booking_changes', 'days_in_waiting_list',
                'adr', 'required_car_parking_spaces',
                'total_of_special_requests']

df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric)

df['agent'] = pd.to_numeric(df['agent']).astype('Int64')
df['company'] = pd.to_numeric(df['company']).astype('Int64')


df['arrival_date_month'] = pd.Categorical(df['arrival_date_month'],
    categories=['January','February','March','April','May','June','July','August',
                'September','October','November','December'],
    ordered=True
)

df['arrival_month_num'] = df['arrival_date_month'].cat.codes + 1

df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'],
                                               )

cat_cols = [
    'hotel','meal','country','market_segment','distribution_channel',
    'reserved_room_type','assigned_room_type','deposit_type',
    'customer_type','reservation_status'
]

for c in cat_cols:
    df[c] = df[c].astype('category')


df = df.drop_duplicates()

df['children'] = df['children'].fillna(0).astype(int)
df['babies']   = df['babies'].fillna(0).astype(int)
df['adults']   = df['adults'].astype(int)

In [5]:
df['hotel'].value_counts()

hotel
City Hotel      53428
Resort Hotel    33968
Name: count, dtype: int64

In [6]:
df['children'].value_counts()

children
0     79032
1      4695
2      3593
3        75
10        1
Name: count, dtype: int64

In [7]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,arrival_month_num
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,<NA>,<NA>,0,Transient,0.00,0,0,Check-Out,2015-07-01,7
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,<NA>,<NA>,0,Transient,0.00,0,0,Check-Out,2015-07-01,7
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,<NA>,<NA>,0,Transient,75.00,0,0,Check-Out,2015-07-02,7
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,304,<NA>,0,Transient,75.00,0,0,Check-Out,2015-07-02,7
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,240,<NA>,0,Transient,98.00,0,1,Check-Out,2015-07-03,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,394,<NA>,0,Transient,96.14,0,0,Check-Out,2017-09-06,8
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,9,<NA>,0,Transient,225.43,0,2,Check-Out,2017-09-07,8
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,9,<NA>,0,Transient,157.71,0,4,Check-Out,2017-09-07,8
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,89,<NA>,0,Transient,104.40,0,0,Check-Out,2017-09-07,8
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,9,<NA>,0,Transient,151.20,0,2,Check-Out,2017-09-07,8

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87396 entries, 0 to 119389
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87396 non-null  category
 1   is_canceled                     87396 non-null  int64
 2   lead_time                       87396 non-null  int64
 3   arrival_date_year               87396 non-null  int64
 4   arrival_date_month              87396 non-null  category
 5   arrival_date_week_number        87396 non-null  int64
 6   arrival_date_day_of_month       87396 non-null  int64
 7   stays_in_weekend_nights         87396 non-null  int64
 8   stays_in_week_nights            87396 non-null  int64
 9   adults                          87396 non-null  int64
 10  children                        87396 non-null  int64
 11  babies                          87396 non-null  int64
 12  meal                            87396 non-null  category
 13  country                         86944 non-null  category
 14  market_segment                  87396 non-null  category
 15  distribution_channel            87396 non-null  category
 16  is_repeated_guest               87396 non-null  int64
 17  previous_cancellations          87396 non-null  int64
 18  previous_bookings_not_canceled  87396 non-null  int64
 19  reserved_room_type              87396 non-null  category
 20  assigned_room_type              87396 non-null  category
 21  booking_changes                 87396 non-null  int64
 22  deposit_type                    87396 non-null  category
 23  agent                           75203 non-null  Int64
 24  company                         5259 non-null   Int64
 25  days_in_waiting_list            87396 non-null  int64
 26  customer_type                   87396 non-null  category
 27  adr                             87396 non-null  float64
 28  required_car_parking_spaces     87396 non-null  int64
 29  total_of_special_requests       87396 non-null  int64
 30  reservation_status              87396 non-null  category
 31  reservation_status_date         87396 non-null  datetime64[ns]
 32  arrival_month_num               87396 non-null  int8
dtypes: Int64(2), category(11), datetime64[ns](1), float64(1), int64(17), int8(1)
memory usage: 15.9 MB

In [9]:
import pandas as pd
import sys

pd.set_option('display.max_info_columns', sys.maxsize)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87396 entries, 0 to 119389
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87396 non-null  category
 1   is_canceled                     87396 non-null  int64
 2   lead_time                       87396 non-null  int64
 3   arrival_date_year               87396 non-null  int64
 4   arrival_date_month              87396 non-null  category
 5   arrival_date_week_number        87396 non-null  int64
 6   arrival_date_day_of_month       87396 non-null  int64
 7   stays_in_weekend_nights         87396 non-null  int64
 8   stays_in_week_nights            87396 non-null  int64
 9   adults                          87396 non-null  int64
 10  children                        87396 non-null  int64
 11  babies                          87396 non-null  int64
 12  meal                            87396 non-null  category
 13  country                         86944 non-null  category
 14  market_segment                  87396 non-null  category
 15  distribution_channel            87396 non-null  category
 16  is_repeated_guest               87396 non-null  int64
 17  previous_cancellations          87396 non-null  int64
 18  previous_bookings_not_canceled  87396 non-null  int64
 19  reserved_room_type              87396 non-null  category
 20  assigned_room_type              87396 non-null  category
 21  booking_changes                 87396 non-null  int64
 22  deposit_type                    87396 non-null  category
 23  agent                           75203 non-null  Int64
 24  company                         5259 non-null   Int64
 25  days_in_waiting_list            87396 non-null  int64
 26  customer_type                   87396 non-null  category
 27  adr                             87396 non-null  float64
 28  required_car_parking_spaces     87396 non-null  int64
 29  total_of_special_requests       87396 non-null  int64
 30  reservation_status              87396 non-null  category
 31  reservation_status_date         87396 non-null  datetime64[ns]
 32  arrival_month_num               87396 non-null  int8
dtypes: Int64(2), category(11), datetime64[ns](1), float64(1), int64(17), int8(1)
memory usage: 15.9 MB

In [10]:
df['children'].value_counts()

children
0     79032
1      4695
2      3593
3        75
10        1
Name: count, dtype: int64

In [11]:
df['reservation_status'].value_counts()

reservation_status
Check-Out    63371
Canceled     23011
No-Show       1014
Name: count, dtype: int64

In [12]:
df['meal'].value_counts()

meal
BB           67978
SC            9481
HB            9085
Undefined      492
FB             360
Name: count, dtype: int64

In [13]:
import numpy as np
import pandas as pd
from pathlib import Path
df = pd.read_csv(Path('/home/admin123/Documents/SAP/Div_academy/data/dirty_cafe_sales.csv'))
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [15]:
df["Quantity"].value_counts()

Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
Name: count, dtype: int64

In [16]:
df2 = df.copy()
df2.drop(df2[df2['Quantity'] == 'UNKNOWN'].index, axis=0,inplace=True)

In [17]:
df2.drop(df2[df2['Quantity'] == 'ERROR'].index,axis=0,inplace=True)

In [18]:
df2['Quantity'].value_counts()

Quantity
5    2013
2    1974
4    1863
3    1849
1    1822
Name: count, dtype: int64

In [19]:
df2['Price Per Unit'].value_counts()

Price Per Unit
3.0        2363
4.0        2242
2.0        1177
5.0        1162
1.0        1107
1.5        1088
ERROR       188
UNKNOWN     159
Name: count, dtype: int64

In [20]:
df2.drop((df2[(df2['Price Per Unit'] == 'ERROR') | (df2['Price Per Unit'] == 'UNKNOWN')]).index,axis=0,inplace=True)
df2

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [21]:
df2['Price Per Unit'].value_counts()

Price Per Unit
3.0    2363
4.0    2242
2.0    1177
5.0    1162
1.0    1107
1.5    1088
Name: count, dtype: int64

In [22]:
df2['Price Per Unit'].dropna(inplace=True)
df2['Price Per Unit'].value_counts()

Price Per Unit
3.0    2363
4.0    2242
2.0    1177
5.0    1162
1.0    1107
1.5    1088
Name: count, dtype: int64

In [23]:
df2

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [24]:
df2['Price Per Unit'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996     True
9997    False
9998     True
9999    False
Name: Price Per Unit, Length: 9312, dtype: bool

In [25]:
df2['Price Per Unit'].value_counts().sum()

np.int64(9139)

In [26]:
df2 = df2.dropna(subset=['Price Per Unit'])

In [27]:
df2['Quantity'] = df2['Quantity'].astype(float)

/tmp/ipykernel_6321/601926169.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Quantity'] = df2['Quantity'].astype(float)

In [28]:
df2['Price Per Unit'] = df2['Price Per Unit'].astype(float)
df2['Price Per Unit']

/tmp/ipykernel_6321/996777844.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Price Per Unit'] = df2['Price Per Unit'].astype(float)

0       2.0
1       3.0
2       1.0
3       5.0
4       2.0
       ...
9993    4.0
9994    4.0
9995    2.0
9997    2.0
9999    4.0
Name: Price Per Unit, Length: 9139, dtype: float64

In [29]:
df2['Total Spent'] = df2['Quantity'] * df2['Price Per Unit']
df2

/tmp/ipykernel_6321/2732881570.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Total Spent'] = df2['Quantity'] * df2['Price Per Unit']

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9993,TXN_4766549,Smoothie,2.0,4.0,8.0,Cash,NaN,2023-10-20
9994,TXN_7851634,UNKNOWN,4.0,4.0,16.0,NaN,NaN,2023-01-08
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,UNKNOWN,2023-08-30
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [30]:
df2[df2['Item'] == 'Coffee']['Price Per Unit'].unique()
df2.groupby('Item')['Price Per Unit'].mean()

Item
Cake        3.000000
Coffee      2.000000
Cookie      1.000000
ERROR       2.951311
Juice       3.000000
Salad       5.000000
Sandwich    4.000000
Smoothie    4.000000
Tea         1.500000
UNKNOWN     2.878594
Name: Price Per Unit, dtype: float64

In [31]:
df2[df2['Item'] == 'ERROR']['Price Per Unit'].value_counts()

Price Per Unit
3.0    76
4.0    57
5.0    38
1.5    34
1.0    33
2.0    29
Name: count, dtype: int64

In [37]:
df2.loc[(df2['Item'] == 'ERROR') & (df2['Price Per Unit'] == 3.0), 'Item'] = 'Cake'
df2.loc[(df2['Item'] == 'ERROR') & (df2['Price Per Unit'] == 4.0), 'Item'] = 'Sandwich'
df2.loc[(df2['Item'] == 'ERROR') & (df2['Price Per Unit'] == 5.0), 'Item'] = 'Salad'
df2.loc[(df2['Item'] == 'ERROR') & (df2['Price Per Unit'] == 1.5), 'Item'] = 'Tea'
df2.loc[(df2['Item'] == 'ERROR') & (df2['Price Per Unit'] == 1.0), 'Item'] = 'Cookie'
df2.loc[(df2['Item'] == 'ERROR') & (df2['Price Per Unit'] == 2.0), 'Item'] = 'Coffee'

df2

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9993,TXN_4766549,Smoothie,2.0,4.0,8.0,Cash,NaN,2023-10-20
9994,TXN_7851634,UNKNOWN,4.0,4.0,16.0,NaN,NaN,2023-01-08
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,UNKNOWN,2023-08-30
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [38]:
df2['Item'].value_counts()

Item
Cake        1135
Coffee      1096
Sandwich    1096
Salad       1081
Juice       1076
Cookie      1026
Tea         1017
Smoothie    1003
UNKNOWN      313
Name: count, dtype: int64

In [39]:
df2.loc[df2['Item'] == 'UNKNOWN', 'Price Per Unit'].value_counts()

Price Per Unit
3.0    74
4.0    66
2.0    46
5.0    44
1.0    43
1.5    40
Name: count, dtype: int64

In [40]:
df2.loc[(df2['Item'] == 'UNKNOWN') & (df2['Price Per Unit'] == 5.0), 'Item'] = 'Salad'
df2.loc[(df2['Item'] == 'UNKNOWN') & (df2['Price Per Unit'] == 1.0), 'Item'] = 'Cookie'
df2.loc[(df2['Item'] == 'UNKNOWN') & (df2['Price Per Unit'] == 1.5), 'Item'] = 'Tea'
df2.loc[(df2['Item'] == 'UNKNOWN') & (df2['Price Per Unit'] == 4.0), 'Item'] = 'Sandwich'
df2.loc[(df2['Item'] == 'UNKNOWN') & (df2['Price Per Unit'] == 2.0), 'Item'] = 'Coffee'
df2.loc[(df2['Item'] == 'UNKNOWN') & (df2['Price Per Unit'] == 3.0), 'Item'] = 'Cake'

df2

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9993,TXN_4766549,Smoothie,2.0,4.0,8.0,Cash,NaN,2023-10-20
9994,TXN_7851634,Sandwich,4.0,4.0,16.0,NaN,NaN,2023-01-08
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,UNKNOWN,2023-08-30
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [42]:
df2.loc[:,'Item'].value_counts()

Item
Cake        1209
Sandwich    1162
Coffee      1142
Salad       1125
Juice       1076
Cookie      1069
Tea         1057
Smoothie    1003
Name: count, dtype: int64

In [53]:
# df2['Quantity'].isna().sum()
# df2['Price Per Unit'].isna().sum()
# df2['Total Spent'].isna().sum()

mask = df2['Quantity'].isna()
df2.loc[mask, ['Quantity','Price Per Unit','Total Spent']]

      Quantity  Price Per Unit  Total Spent
66         NaN             3.0          NaN
341        NaN             1.0          NaN
376        NaN             2.0          NaN
412        NaN             3.0          NaN
532        NaN             1.0          NaN
...        ...             ...          ...
9634       NaN             3.0          NaN
9844       NaN             5.0          NaN
9869       NaN             2.0          NaN
9887       NaN             5.0          NaN
9896       NaN             2.0          NaN

[133 rows x 3 columns]

In [64]:
mask2 = df2.loc[:,['Quantity','Price Per Unit','Total Spent']].isna().any(axis=1)
df2.drop(df2.loc[mask2].index, axis='rows',inplace=True)
df2

/tmp/ipykernel_6321/3282853994.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(df2.loc[mask2].index, axis='rows',inplace=True)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9993,TXN_4766549,Smoothie,2.0,4.0,8.0,Cash,NaN,2023-10-20
9994,TXN_7851634,Sandwich,4.0,4.0,16.0,NaN,NaN,2023-01-08
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,UNKNOWN,2023-08-30
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [65]:
df2['Payment Method'].value_counts()

Payment Method
Digital Wallet    2068
Credit Card       2047
Cash              2044
ERROR              271
UNKNOWN            266
Name: count, dtype: int64

In [69]:
df2['Transaction Date'].value_counts()

Transaction Date
UNKNOWN       142
ERROR         131
2023-06-16     38
2023-07-21     37
2023-07-24     35
             ...
2023-07-22     13
2023-03-11     13
2023-04-27     12
2023-08-08     12
2023-02-17     12
Name: count, Length: 367, dtype: int64