In [2]:
import seaborn as sns
import pandas as pd
import numpy as np

df = sns.load_dataset("titanic")
df.head()

df[df['sex'] == 'female']

df[df['age'] > 18 and df['sex'] == 'female']
df.loc[:,['survived','pclass','age','fare']]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [5]:
df.head(100)
df2 = df.loc[:,['age','fare','survived']]
# df2[df2['fare'] < 20] = np.nan
# df
df2

      age     fare  survived
0    22.0   7.2500         0
1    38.0  71.2833         1
2    26.0   7.9250         1
3    35.0  53.1000         1
4    35.0   8.0500         0
..    ...      ...       ...
886  27.0  13.0000         0
887  19.0  30.0000         1
888   NaN  23.4500         0
889  26.0  30.0000         1
890  32.0   7.7500         0

[891 rows x 3 columns]

In [11]:
def myfunction(age):
    if pd.isna(age):
        return 'Unknown'
    elif age < 18:
        return 'Child'
    elif age >=18 and age < 60:
        return 'Adult'
    else:
        return "Senior"
    
df2['age_group'] = df2['age'].apply(myfunction)
df2

      age     fare  survived age_group
0    22.0   7.2500         0     Adult
1    38.0  71.2833         1     Adult
2    26.0   7.9250         1     Adult
3    35.0  53.1000         1     Adult
4    35.0   8.0500         0     Adult
..    ...      ...       ...       ...
886  27.0  13.0000         0     Adult
887  19.0  30.0000         1     Adult
888   NaN  23.4500         0   Unknown
889  26.0  30.0000         1     Adult
890  32.0   7.7500         0     Adult

[891 rows x 4 columns]

In [18]:
def function2(age):
    if pd.isna(age):
        return round(df2['age'].mean())
    else:
        return age

df2['age_filled'] = df2['age'].apply(function2)
df2

      age     fare  survived age_group  age_filled
0    22.0   7.2500         0     Adult        22.0
1    38.0  71.2833         1     Adult        38.0
2    26.0   7.9250         1     Adult        26.0
3    35.0  53.1000         1     Adult        35.0
4    35.0   8.0500         0     Adult        35.0
..    ...      ...       ...       ...         ...
886  27.0  13.0000         0     Adult        27.0
887  19.0  30.0000         1     Adult        19.0
888   NaN  23.4500         0   Unknown        30.0
889  26.0  30.0000         1     Adult        26.0
890  32.0   7.7500         0     Adult        32.0

[891 rows x 5 columns]

In [7]:
import seaborn as sns
import pandas as pd
import numpy as np

pop = pd.read_csv('/home/admin123/Documents/SAP/Div_academy/data/state-population.csv')
areas = pd.read_csv('/home/admin123/Documents/SAP/Div_academy/data/state-areas.csv')
abbrevs = pd.read_csv('/home/admin123/Documents/SAP/Div_academy/data/state-abbrevs.csv')

pop.head()

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [5]:
areas.head()

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [6]:
abbrevs.head()

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [10]:
merged = pd.merge(
    pop,
    abbrevs,
    how='outer',
    left_on='state/region',
    right_on='abbreviation'
)
merged = merged.drop('abbreviation', axis=1)
merged.head()

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska
3           AK  under18  1991    182180.0  Alaska
4           AK  under18  1992    184878.0  Alaska

In [11]:
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [14]:
merged[merged['population'].isnull()].head()

     state/region     ages  year  population state
1872           PR  under18  1990         NaN   NaN
1873           PR    total  1990         NaN   NaN
1874           PR    total  1991         NaN   NaN
1875           PR  under18  1991         NaN   NaN
1876           PR    total  1993         NaN   NaN

In [16]:
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool